### ISSUE TITLE
crash when psalm editing: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by alelk** [alelk/pws-android#16]
Method: com.alelk.pws.pwapp.activity.PsalmEditActivity.populateUIFromPsalmHolder

Exception: java.lang.ArrayIndexOutOfBoundsException

<img width="1312" alt="image" src="https://github.com/alelk/pws-android/assets/8504448/d57acba0-791b-4d3f-8c10-8b8ad3df16f4">

**Comment by MykhailoDmytriakha** [comment]
@alelk this issue should be fixed by last two PRs, when we had a case "tonality is not defined"

**Comment by alelk** [comment]
fixed
